//go:build go1.22

// Package httpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package httpapi

import (
	"fmt"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Defines values for CatalogCurrency.
const (
	CatalogCurrencyEUR CatalogCurrency = "EUR"
)

// Valid indicates whether the value is a known member of the CatalogCurrency enum.
func (e CatalogCurrency) Valid() bool {
	switch e {
	case CatalogCurrencyEUR:
		return true
	default:
		return false
	}
}

// Defines values for DiscountPercent.
const (
	DiscountPercentN0  DiscountPercent = 0
	DiscountPercentN10 DiscountPercent = 10
	DiscountPercentN20 DiscountPercent = 20
)

// Valid indicates whether the value is a known member of the DiscountPercent enum.
func (e DiscountPercent) Valid() bool {
	switch e {
	case DiscountPercentN0:
		return true
	case DiscountPercentN10:
		return true
	case DiscountPercentN20:
		return true
	default:
		return false
	}
}

// Defines values for Film.
const (
	FilmBttf1 Film = "bttf_1"
	FilmBttf2 Film = "bttf_2"
	FilmBttf3 Film = "bttf_3"
	FilmOther Film = "other"
)

// Valid indicates whether the value is a known member of the Film enum.
func (e Film) Valid() bool {
	switch e {
	case FilmBttf1:
		return true
	case FilmBttf2:
		return true
	case FilmBttf3:
		return true
	case FilmOther:
		return true
	default:
		return false
	}
}

// Defines values for GuardOutcomeVerdict.
const (
	GuardOutcomeVerdictInjection GuardOutcomeVerdict = "injection"
	GuardOutcomeVerdictInvalid   GuardOutcomeVerdict = "invalid"
	GuardOutcomeVerdictValid     GuardOutcomeVerdict = "valid"
)

// Valid indicates whether the value is a known member of the GuardOutcomeVerdict enum.
func (e GuardOutcomeVerdict) Valid() bool {
	switch e {
	case GuardOutcomeVerdictInjection:
		return true
	case GuardOutcomeVerdictInvalid:
		return true
	case GuardOutcomeVerdictValid:
		return true
	default:
		return false
	}
}

// Defines values for HealthEngines.
const (
	HealthEnginesFake HealthEngines = "fake"
	HealthEnginesLive HealthEngines = "live"
)

// Valid indicates whether the value is a known member of the HealthEngines enum.
func (e HealthEngines) Valid() bool {
	switch e {
	case HealthEnginesFake:
		return true
	case HealthEnginesLive:
		return true
	default:
		return false
	}
}

// Defines values for HealthImplementation.
const (
	HealthImplementationGo         HealthImplementation = "go"
	HealthImplementationPython     HealthImplementation = "python"
	HealthImplementationTypescript HealthImplementation = "typescript"
)

// Valid indicates whether the value is a known member of the HealthImplementation enum.
func (e HealthImplementation) Valid() bool {
	switch e {
	case HealthImplementationGo:
		return true
	case HealthImplementationPython:
		return true
	case HealthImplementationTypescript:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	HealthStatusOk HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case HealthStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for JudgeCheckCheck.
const (
	JudgeCheckCheckAsked    JudgeCheckCheck = "asked"
	JudgeCheckCheckIdentity JudgeCheckCheck = "identity"
	JudgeCheckCheckMissing  JudgeCheckCheck = "missing"
	JudgeCheckCheckQuantity JudgeCheckCheck = "quantity"
)

// Valid indicates whether the value is a known member of the JudgeCheckCheck enum.
func (e JudgeCheckCheck) Valid() bool {
	switch e {
	case JudgeCheckCheckAsked:
		return true
	case JudgeCheckCheckIdentity:
		return true
	case JudgeCheckCheckMissing:
		return true
	case JudgeCheckCheckQuantity:
		return true
	default:
		return false
	}
}

// Defines values for ProblemCode.
const (
	ProblemCodeEmptyCart         ProblemCode = "empty_cart"
	ProblemCodeEngineUnavailable ProblemCode = "engine_unavailable"
	ProblemCodeInjection         ProblemCode = "injection"
	ProblemCodeInternal          ProblemCode = "internal"
	ProblemCodeInvalidRequest    ProblemCode = "invalid_request"
	ProblemCodeMalformedRequest  ProblemCode = "malformed_request"
	ProblemCodeMethodNotAllowed  ProblemCode = "method_not_allowed"
	ProblemCodeNoFilm            ProblemCode = "no_film"
	ProblemCodeNotFound          ProblemCode = "not_found"
	ProblemCodePayloadTooLarge   ProblemCode = "payload_too_large"
	ProblemCodeQuantityTooLarge  ProblemCode = "quantity_too_large"
	ProblemCodeTooLong           ProblemCode = "too_long"
	ProblemCodeUnfaithfulReading ProblemCode = "unfaithful_reading"
)

// Valid indicates whether the value is a known member of the ProblemCode enum.
func (e ProblemCode) Valid() bool {
	switch e {
	case ProblemCodeEmptyCart:
		return true
	case ProblemCodeEngineUnavailable:
		return true
	case ProblemCodeInjection:
		return true
	case ProblemCodeInternal:
		return true
	case ProblemCodeInvalidRequest:
		return true
	case ProblemCodeMalformedRequest:
		return true
	case ProblemCodeMethodNotAllowed:
		return true
	case ProblemCodeNoFilm:
		return true
	case ProblemCodeNotFound:
		return true
	case ProblemCodePayloadTooLarge:
		return true
	case ProblemCodeQuantityTooLarge:
		return true
	case ProblemCodeTooLong:
		return true
	case ProblemCodeUnfaithfulReading:
		return true
	default:
		return false
	}
}

// Defines values for QuoteCurrency.
const (
	QuoteCurrencyEUR QuoteCurrency = "EUR"
)

// Valid indicates whether the value is a known member of the QuoteCurrency enum.
func (e QuoteCurrency) Valid() bool {
	switch e {
	case QuoteCurrencyEUR:
		return true
	default:
		return false
	}
}

// Defines values for StageUsageStage.
const (
	StageUsageStageGuard    StageUsageStage = "guard"
	StageUsageStageIdentify StageUsageStage = "identify"
	StageUsageStageJudge    StageUsageStage = "judge"
	StageUsageStageParse    StageUsageStage = "parse"
	StageUsageStagePrepare  StageUsageStage = "prepare"
	StageUsageStagePrice    StageUsageStage = "price"
)

// Valid indicates whether the value is a known member of the StageUsageStage enum.
func (e StageUsageStage) Valid() bool {
	switch e {
	case StageUsageStageGuard:
		return true
	case StageUsageStageIdentify:
		return true
	case StageUsageStageJudge:
		return true
	case StageUsageStageParse:
		return true
	case StageUsageStagePrepare:
		return true
	case StageUsageStagePrice:
		return true
	default:
		return false
	}
}

// Defines values for UsageEngines.
const (
	UsageEnginesFake UsageEngines = "fake"
	UsageEnginesLive UsageEngines = "live"
)

// Valid indicates whether the value is a known member of the UsageEngines enum.
func (e UsageEngines) Valid() bool {
	switch e {
	case UsageEnginesFake:
		return true
	case UsageEnginesLive:
		return true
	default:
		return false
	}
}

// Defines values for UsageImplementation.
const (
	UsageImplementationGo         UsageImplementation = "go"
	UsageImplementationPython     UsageImplementation = "python"
	UsageImplementationTypescript UsageImplementation = "typescript"
)

// Valid indicates whether the value is a known member of the UsageImplementation enum.
func (e UsageImplementation) Valid() bool {
	switch e {
	case UsageImplementationGo:
		return true
	case UsageImplementationPython:
		return true
	case UsageImplementationTypescript:
		return true
	default:
		return false
	}
}

// Catalog defines model for Catalog.
type Catalog struct {
	Currency CatalogCurrency `json:"currency"`

	// Films The saga volumes, in order.
	Films                   []CatalogFilm  `json:"films"`
	Limits                  Limits         `json:"limits"`
	OtherFilmUnitPriceCents int            `json:"other_film_unit_price_cents"`
	SagaDiscounts           []SagaDiscount `json:"saga_discounts"`
}

// CatalogCurrency defines model for Catalog.Currency.
type CatalogCurrency string

// CatalogFilm defines model for CatalogFilm.
type CatalogFilm struct {
	// Id What a title was identified as. `other` is any film outside the saga.
	Id             Film   `json:"id"`
	Title          string `json:"title"`
	UnitPriceCents int    `json:"unit_price_cents"`
	Volume         int    `json:"volume"`
}

// Discount The saga discount. `percent` is 0 when it does not apply.
type Discount struct {
	AmountCents int `json:"amount_cents"`

	// BaseCents Subtotal of the Back to the Future DVDs, on which the percent applies.
	BaseCents       int             `json:"base_cents"`
	DistinctVolumes int             `json:"distinct_volumes"`
	Percent         DiscountPercent `json:"percent"`
}

// DiscountPercent defines model for Discount.Percent.
type DiscountPercent int

// Film What a title was identified as. `other` is any film outside the saga.
type Film string

// GuardOutcome defines model for GuardOutcome.
type GuardOutcome struct {
	Confidence    float64             `json:"confidence"`
	Probabilities *map[string]float64 `json:"probabilities,omitempty"`
	Verdict       GuardOutcomeVerdict `json:"verdict"`
}

// GuardOutcomeVerdict defines model for GuardOutcome.Verdict.
type GuardOutcomeVerdict string

// Health defines model for Health.
type Health struct {
	Engines        HealthEngines        `json:"engines"`
	Implementation HealthImplementation `json:"implementation"`
	Status         HealthStatus         `json:"status"`

	// Tracing Whether traces are exported to Langfuse.
	Tracing bool   `json:"tracing"`
	Version string `json:"version"`
}

// HealthEngines defines model for Health.Engines.
type HealthEngines string

// HealthImplementation defines model for Health.Implementation.
type HealthImplementation string

// HealthStatus defines model for Health.Status.
type HealthStatus string

// JudgeCheck defines model for JudgeCheck.
type JudgeCheck struct {
	// Check `asked`: the customer asks for this film (nothing invented).
	// `identity`: the title is the film it was identified as.
	// `quantity`: the customer asks for this many copies.
	// `missing`: no film asked for is left out of the reading.
	Check JudgeCheckCheck `json:"check"`

	// Label What the check was put about (a line, or the whole reading).
	Label string  `json:"label"`
	Score float64 `json:"score"`
}

// JudgeCheckCheck `asked`: the customer asks for this film (nothing invented).
// `identity`: the title is the film it was identified as.
// `quantity`: the customer asks for this many copies.
// `missing`: no film asked for is left out of the reading.
type JudgeCheckCheck string

// JudgeOutcome The judge puts one short question per observable fact and keeps the
// worst answer as the score. The cart is priced only when
// `score >= threshold`.
type JudgeOutcome struct {
	Checks    []JudgeCheck `json:"checks"`
	Score     float64      `json:"score"`
	Threshold float64      `json:"threshold"`
}

// Limits defines model for Limits.
type Limits struct {
	MaxBodyBytes int `json:"max_body_bytes"`

	// MaxCopiesPerTitle Most copies of one title a cart may ask for.
	MaxCopiesPerTitle int `json:"max_copies_per_title"`
	MaxInputTokens    int `json:"max_input_tokens"`
}

// Problem RFC 9457 problem details, with a stable `code` and the facts behind it.
type Problem struct {
	// Code - `malformed_request` (400): not JSON, or not a `QuoteRequest`.
	// - `payload_too_large` (413): body over `limits.max_body_bytes`.
	// - `empty_cart` (422): nothing but blanks.
	// - `too_long` (422): over `limits.max_input_tokens`.
	// - `injection` (422): the guard sees an attempt to instruct or hack the system.
	// - `invalid_request` (422): the guard sees no cart — gibberish, a language not understood, off topic.
	// - `no_film` (422): valid, but the parser reads no film to buy.
	// - `quantity_too_large` (422): a title is asked in more than
	//   `limits.max_copies_per_title` copies. Identical titles (case and
	//   spaces aside) are merged first; two spellings of one volume are two titles.
	// - `unfaithful_reading` (422): the judge does not hold the reading faithful.
	// - `engine_unavailable` (502): a model engine failed.
	// - `not_found` (404), `method_not_allowed` (405), `internal` (500).
	Code   ProblemCode   `json:"code"`
	Detail *string       `json:"detail,omitempty"`
	Guard  *GuardOutcome `json:"guard,omitempty"`

	// Judge The judge puts one short question per observable fact and keeps the
	// worst answer as the score. The cart is priced only when
	// `score >= threshold`.
	Judge *JudgeOutcome `json:"judge,omitempty"`

	// Quantity The title asked in too many copies (`quantity_too_large`).
	Quantity  *Problem_Quantity `json:"quantity,omitempty"`
	RequestId *string           `json:"request_id,omitempty"`
	Status    int               `json:"status"`
	Title     string            `json:"title"`
	Tokens    *Problem_Tokens   `json:"tokens,omitempty"`

	// Type Examples: /problems/injection
	Type  string `json:"type"`
	Usage *Usage `json:"usage,omitempty"`
}

// Problem_Quantity The title asked in too many copies (`quantity_too_large`).
type Problem_Quantity struct {
	Count int    `json:"count"`
	Max   int    `json:"max"`
	Title string `json:"title"`
}

// Problem_Tokens defines model for Problem.Tokens.
type Problem_Tokens struct {
	Count int `json:"count"`
	Max   int `json:"max"`
}

// ProblemCode - `malformed_request` (400): not JSON, or not a `QuoteRequest`.
//   - `payload_too_large` (413): body over `limits.max_body_bytes`.
//   - `empty_cart` (422): nothing but blanks.
//   - `too_long` (422): over `limits.max_input_tokens`.
//   - `injection` (422): the guard sees an attempt to instruct or hack the system.
//   - `invalid_request` (422): the guard sees no cart — gibberish, a language not understood, off topic.
//   - `no_film` (422): valid, but the parser reads no film to buy.
//   - `quantity_too_large` (422): a title is asked in more than
//     `limits.max_copies_per_title` copies. Identical titles (case and
//     spaces aside) are merged first; two spellings of one volume are two titles.
//   - `unfaithful_reading` (422): the judge does not hold the reading faithful.
//   - `engine_unavailable` (502): a model engine failed.
//   - `not_found` (404), `method_not_allowed` (405), `internal` (500).
type ProblemCode string

// Quote defines model for Quote.
type Quote struct {
	CreatedAt time.Time     `json:"created_at"`
	Currency  QuoteCurrency `json:"currency"`

	// Discount The saga discount. `percent` is 0 when it does not apply.
	Discount Discount `json:"discount"`

	// Id Identifier of this quote (also the Langfuse trace name suffix).
	//
	// Examples: q_7f3a9c2e
	Id string `json:"id"`

	// Judge The judge puts one short question per observable fact and keeps the
	// worst answer as the score. The cart is priced only when
	// `score >= threshold`.
	Judge JudgeOutcome `json:"judge"`
	Lines []QuoteLine  `json:"lines"`

	// SubtotalCents Sum of the lines before discount.
	SubtotalCents int `json:"subtotal_cents"`

	// TotalCents What the customer pays.
	TotalCents int   `json:"total_cents"`
	Usage      Usage `json:"usage"`
}

// QuoteCurrency defines model for Quote.Currency.
type QuoteCurrency string

// QuoteLine defines model for QuoteLine.
type QuoteLine struct {
	// Confidence Calibrated confidence of the identification.
	Confidence float64 `json:"confidence"`

	// Film What a title was identified as. `other` is any film outside the saga.
	Film Film `json:"film"`

	// Quantity Copies of this title; at most `limits.max_copies_per_title`.
	Quantity int `json:"quantity"`

	// SubtotalCents unit price × quantity, before discount.
	SubtotalCents int `json:"subtotal_cents"`

	// Title The title as the customer wrote it.
	Title          string `json:"title"`
	UnitPriceCents int    `json:"unit_price_cents"`
}

// QuoteRequest defines model for QuoteRequest.
type QuoteRequest struct {
	// Cart The cart as the customer wrote it. Empty or blank is rejected with `empty_cart`.
	Cart string `json:"cart"`
}

// SagaDiscount defines model for SagaDiscount.
type SagaDiscount struct {
	DistinctVolumes int `json:"distinct_volumes"`
	Percent         int `json:"percent"`
}

// StageUsage defines model for StageUsage.
type StageUsage struct {
	Calls      int     `json:"calls"`
	CostUsd    float64 `json:"cost_usd"`
	DurationMs int     `json:"duration_ms"`

	// Engine Examples: jev-1.13, openai/gpt-6-luna, fake, local
	Engine string          `json:"engine"`
	Model  *string         `json:"model,omitempty"`
	Stage  StageUsageStage `json:"stage"`

	// Tokens Input tokens counted (prepare).
	Tokens *int `json:"tokens,omitempty"`
}

// StageUsageStage defines model for StageUsage.Stage.
type StageUsageStage string

// Usage defines model for Usage.
type Usage struct {
	CostUsd    float64 `json:"cost_usd"`
	DurationMs int     `json:"duration_ms"`

	// Engines `fake` engines are deterministic stand-ins for tests; never in production.
	Engines        UsageEngines        `json:"engines"`
	Implementation UsageImplementation `json:"implementation"`
	Stages         []StageUsage        `json:"stages"`

	// TraceId The trace of this request, when tracing is on.
	TraceId *string `json:"trace_id,omitempty"`
}

// UsageEngines `fake` engines are deterministic stand-ins for tests; never in production.
type UsageEngines string

// UsageImplementation defines model for Usage.Implementation.
type UsageImplementation string

// RequestId defines model for RequestId.
type RequestId = string

// SessionId defines model for SessionId.
type SessionId = string

// UserId defines model for UserId.
type UserId = string

// EngineUnavailable RFC 9457 problem details, with a stable `code` and the facts behind it.
type EngineUnavailable = Problem

// Internal RFC 9457 problem details, with a stable `code` and the facts behind it.
type Internal = Problem

// MalformedRequest RFC 9457 problem details, with a stable `code` and the facts behind it.
type MalformedRequest = Problem

// PayloadTooLarge RFC 9457 problem details, with a stable `code` and the facts behind it.
type PayloadTooLarge = Problem

// Rejected RFC 9457 problem details, with a stable `code` and the facts behind it.
type Rejected = Problem

// CreateQuoteParams defines parameters for CreateQuote.
type CreateQuoteParams struct {
	// XUserId Who asks (the username of the session). Traced as the Langfuse user.
	XUserId *UserId `json:"X-User-Id,omitempty"`

	// XSessionId The client session. Traced as the Langfuse session.
	XSessionId *SessionId `json:"X-Session-Id,omitempty"`

	// XRequestId Correlation id; generated when absent, echoed in the response.
	XRequestId *RequestId `json:"X-Request-Id,omitempty"`
}

// CreateQuoteJSONRequestBody defines body for CreateQuote for application/json ContentType.
type CreateQuoteJSONRequestBody = QuoteRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetHealth Liveness, and which implementation and engines answer.
	// (GET /healthz)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// GetCatalog The films the shop prices, the saga discounts and the input limits.
	// (GET /v1/catalog)
	GetCatalog(w http.ResponseWriter, r *http.Request)
	// CreateQuote Read a free-text cart and price it.
	// (POST /v1/quotes)
	CreateQuote(w http.ResponseWriter, r *http.Request, params CreateQuoteParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCatalog operation middleware
func (siw *ServerInterfaceWrapper) GetCatalog(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCatalog(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateQuote operation middleware
func (siw *ServerInterfaceWrapper) CreateQuote(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateQuoteParams

	headers := r.Header

	// ------------- Optional header parameter "X-User-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-User-Id")]; found {
		var XUserId UserId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-User-Id", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-User-Id", valueList[0], &XUserId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-User-Id", Err: err})
			return
		}

		params.XUserId = &XUserId

	}

	// ------------- Optional header parameter "X-Session-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Session-Id")]; found {
		var XSessionId SessionId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Session-Id", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Session-Id", valueList[0], &XSessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Session-Id", Err: err})
			return
		}

		params.XSessionId = &XSessionId

	}

	// ------------- Optional header parameter "X-Request-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Request-Id")]; found {
		var XRequestId RequestId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Request-Id", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Request-Id", valueList[0], &XRequestId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Request-Id", Err: err})
			return
		}

		params.XRequestId = &XRequestId

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateQuote(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/healthz", wrapper.GetHealth)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/catalog", wrapper.GetCatalog)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/quotes", wrapper.CreateQuote)

	return m
}
