# generated by datamodel-codegen:
#   filename:  openapi.yaml

from __future__ import annotations

from enum import IntEnum, StrEnum
from typing import Annotated, Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class QuoteRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    cart: Annotated[
        str, Field(description="The cart as the customer wrote it. Empty or blank is rejected with `empty_cart`.")
    ]


class Film(StrEnum):
    """
    What a title was identified as. `other` is any film outside the saga.
    """

    bttf_1 = "bttf_1"
    bttf_2 = "bttf_2"
    bttf_3 = "bttf_3"
    other = "other"


class QuoteLine(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: Annotated[str, Field(description="The title as the customer wrote it.")]
    quantity: Annotated[
        int, Field(description="Copies of this title; at most `limits.max_copies_per_title`.", ge=1, le=1000)
    ]
    film: Film
    confidence: Annotated[float, Field(description="Calibrated confidence of the identification.", ge=0.0, le=1.0)]
    unit_price_cents: Annotated[int, Field(ge=0)]
    subtotal_cents: Annotated[int, Field(description="unit price × quantity, before discount.", ge=0)]


class Percent(IntEnum):
    integer_0 = 0
    integer_10 = 10
    integer_20 = 20


class Discount(BaseModel):
    """
    The saga discount. `percent` is 0 when it does not apply.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    distinct_volumes: Annotated[int, Field(ge=0, le=3)]
    percent: Percent
    base_cents: Annotated[
        int, Field(description="Subtotal of the Back to the Future DVDs, on which the percent applies.", ge=0)
    ]
    amount_cents: Annotated[int, Field(ge=0)]


class Verdict(StrEnum):
    valid = "valid"
    injection = "injection"
    invalid = "invalid"


class Questions(BaseModel):
    """
    The two facts the guard asks about, each in a request of its own:
    `order`, the probability that the message orders films; `steer`,
    the probability that some of it speaks to the system rather than
    to the shop. The verdict's probabilities are made of them:
    injection = steer, valid = (1 − steer) × order,
    invalid = (1 − steer) × (1 − order); the verdict is the likeliest
    and `confidence` its probability.

    """

    model_config = ConfigDict(
        extra="forbid",
    )
    order: Annotated[float, Field(ge=0.0, le=1.0)]
    steer: Annotated[float, Field(ge=0.0, le=1.0)]


class GuardOutcome(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    verdict: Verdict
    confidence: Annotated[float, Field(ge=0.0, le=1.0)]
    probabilities: dict[str, float] | None = None
    questions: Annotated[
        Questions | None,
        Field(
            description="The two facts the guard asks about, each in a request of its own:\n`order`, the probability that the message orders films; `steer`,\nthe probability that some of it speaks to the system rather than\nto the shop. The verdict's probabilities are made of them:\ninjection = steer, valid = (1 − steer) × order,\ninvalid = (1 − steer) × (1 − order); the verdict is the likeliest\nand `confidence` its probability.\n"
        ),
    ] = None


class Check(StrEnum):
    """
    `asked`: the customer asks for this film (nothing invented).
    `identity`: the title is the film it was identified as.
    `count`: the reading and the recount give this film the same
    number of copies (1) or not (0); one per film either reading has,
    `other` counting every film outside the saga together.
    `missing`: no film asked for is left out of the reading.

    """

    asked = "asked"
    identity = "identity"
    count = "count"
    missing = "missing"


class JudgeCheck(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    check: Annotated[
        Check,
        Field(
            description="`asked`: the customer asks for this film (nothing invented).\n`identity`: the title is the film it was identified as.\n`count`: the reading and the recount give this film the same\nnumber of copies (1) or not (0); one per film either reading has,\n`other` counting every film outside the saga together.\n`missing`: no film asked for is left out of the reading.\n"
        ),
    ]
    label: Annotated[
        str,
        Field(
            description='What the check was put about: a line, the whole reading, or for\n`count` the film and both counts ("bttf_2: 1 read, 2 recounted").\n'
        ),
    ]
    score: Annotated[float, Field(ge=0.0, le=1.0)]


class Implementation(StrEnum):
    go = "go"
    python = "python"
    typescript = "typescript"


class Engines(StrEnum):
    """
    `fake` engines are deterministic stand-ins for tests; never in production.
    """

    live = "live"
    fake = "fake"


class Stage(StrEnum):
    prepare = "prepare"
    guard = "guard"
    parse = "parse"
    recount = "recount"
    identify = "identify"
    judge = "judge"
    price = "price"


class StageUsage(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    stage: Stage
    engine: Annotated[str, Field(examples=["jev-1.13", "openai/gpt-6-luna", "fake", "local"])]
    model: str | None = None
    calls: Annotated[int, Field(ge=0)]
    duration_ms: Annotated[int, Field(ge=0)]
    cost_usd: Annotated[float, Field(ge=0.0)]
    tokens: Annotated[int | None, Field(description="Input tokens counted (prepare).", ge=0)] = None
    degraded: Annotated[
        bool | None,
        Field(
            description="The stage failed (an engine down, an answer off its schema, too slow) and the quote was made without it. Only `recount` can be degraded: it is a second opinion, and the judge is still the guard. Absent when the stage did its work; true once, over the readings, when it did not."
        ),
    ] = None


class Tokens(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    count: int
    max: int


class Quantity(BaseModel):
    """
    The title asked in too many copies (`quantity_too_large`).
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    count: int
    max: int


class ProblemCode(StrEnum):
    """
    - `malformed_request` (400): not JSON, or not a `QuoteRequest`.
    - `payload_too_large` (413): body over `limits.max_body_bytes`.
    - `empty_cart` (422): nothing but blanks.
    - `too_long` (422): over `limits.max_input_tokens`.
    - `injection` (422): the guard sees an attempt to instruct or hack the system.
    - `invalid_request` (422): the guard sees no cart — gibberish, a language not understood, off topic.
    - `no_film` (422): valid, but the parser reads no film to buy.
    - `quantity_too_large` (422): a title is asked in more than
      `limits.max_copies_per_title` copies. Identical titles (case and
      spaces aside) are merged first; two spellings of one volume are two titles.
    - `unfaithful_reading` (422): the judge does not hold the reading faithful.
    - `engine_unavailable` (502): a model engine failed.
    - `quantity_unverified` (503): the quantities could not be cross-checked
      (the recount failed) and a line asks for more than one copy; retry.
    - `not_found` (404), `method_not_allowed` (405), `internal` (500).

    """

    malformed_request = "malformed_request"
    payload_too_large = "payload_too_large"
    empty_cart = "empty_cart"
    too_long = "too_long"
    injection = "injection"
    invalid_request = "invalid_request"
    no_film = "no_film"
    quantity_too_large = "quantity_too_large"
    unfaithful_reading = "unfaithful_reading"
    engine_unavailable = "engine_unavailable"
    quantity_unverified = "quantity_unverified"
    not_found = "not_found"
    method_not_allowed = "method_not_allowed"
    internal = "internal"


class Engines1(StrEnum):
    live = "live"
    fake = "fake"


class Prompts(BaseModel):
    """
    The version of each prompt file the service runs (`prompts/`):
    the first 8 hex digits of the SHA-256 of the file's bytes. Two
    implementations with the same versions ask the models the same
    questions; the system bench compares only those.

    """

    model_config = ConfigDict(
        extra="forbid",
    )
    guard: Annotated[str, Field(pattern="^[0-9a-f]{8}$")]
    parse: Annotated[str, Field(pattern="^[0-9a-f]{8}$")]
    identify: Annotated[str, Field(pattern="^[0-9a-f]{8}$")]
    judge: Annotated[str, Field(pattern="^[0-9a-f]{8}$")]


class Health(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    status: Literal["ok"]
    implementation: Implementation
    version: str
    engines: Engines1
    tracing: Annotated[bool, Field(description="Whether traces are exported to Langfuse.")]
    prompts: Annotated[
        Prompts,
        Field(
            description="The version of each prompt file the service runs (`prompts/`):\nthe first 8 hex digits of the SHA-256 of the file's bytes. Two\nimplementations with the same versions ask the models the same\nquestions; the system bench compares only those.\n"
        ),
    ]


class CatalogFilm(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: Film
    title: str
    volume: Annotated[int, Field(ge=1)]
    unit_price_cents: Annotated[int, Field(ge=0)]


class SagaDiscount(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    distinct_volumes: Annotated[int, Field(ge=1)]
    percent: Annotated[int, Field(ge=0, le=100)]


class Limits(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    max_reading_attempts: Annotated[
        int,
        Field(
            description="Most readings of one cart, the first included, before it is refused as `unfaithful_reading`.",
            ge=1,
        ),
    ]
    max_body_bytes: Annotated[int, Field(ge=1)]
    max_input_tokens: Annotated[int, Field(ge=1)]
    max_copies_per_title: Annotated[int, Field(description="Most copies of one title a cart may ask for.", ge=1)]


class JudgeOutcome(BaseModel):
    """
    The judge puts one short question per observable fact and keeps the
    worst answer as the score. The cart is priced only when
    `score >= threshold`. A reading the judge refuses is read again, told
    what failed, up to `limits.max_reading_attempts` readings (3 by default);
    the outcome is that of the last reading judged.

    """

    model_config = ConfigDict(
        extra="forbid",
    )
    attempts: Annotated[int, Field(description="How many readings were made before this outcome.", ge=1)]
    score: Annotated[float, Field(ge=0.0, le=1.0)]
    threshold: Annotated[float, Field(ge=0.0, le=1.0)]
    checks: list[JudgeCheck]


class Usage(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    implementation: Implementation
    engines: Annotated[
        Engines, Field(description="`fake` engines are deterministic stand-ins for tests; never in production.")
    ]
    duration_ms: Annotated[int, Field(ge=0)]
    cost_usd: Annotated[float, Field(ge=0.0)]
    trace_id: Annotated[str | None, Field(description="The trace of this request, when tracing is on.")] = None
    stages: list[StageUsage]


class Problem(BaseModel):
    """
    RFC 9457 problem details, with a stable `code` and the facts behind it.
    """

    type: Annotated[str, Field(examples=["/problems/injection"])]
    title: str
    status: int
    code: ProblemCode
    detail: str | None = None
    request_id: str | None = None
    guard: GuardOutcome | None = None
    judge: JudgeOutcome | None = None
    tokens: Tokens | None = None
    quantity: Annotated[
        Quantity | None, Field(description="The title asked in too many copies (`quantity_too_large`).")
    ] = None
    usage: Usage | None = None


class Catalog(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    currency: Literal["EUR"]
    films: Annotated[list[CatalogFilm], Field(description="The saga volumes, in order.")]
    other_film_unit_price_cents: Annotated[int, Field(ge=0)]
    saga_discounts: list[SagaDiscount]
    limits: Limits


class Quote(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: Annotated[
        str,
        Field(description="Identifier of this quote (also the Langfuse trace name suffix).", examples=["q_7f3a9c2e"]),
    ]
    currency: Literal["EUR"]
    lines: Annotated[list[QuoteLine], Field(min_length=1)]
    subtotal_cents: Annotated[int, Field(description="Sum of the lines before discount.", ge=0)]
    discount: Discount
    total_cents: Annotated[int, Field(description="What the customer pays.", ge=0)]
    judge: JudgeOutcome
    usage: Usage
    created_at: AwareDatetime
